name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-dev.2.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^5.0.0
  notus:
    path: ../notus
  quill_delta:
    path: ../../quill_delta_fork
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  characters: ^1.0.0
  image_picker: ^0.6.7+21
  video_player: ^1.0.1
  file_picker: ^2.1.5+1
  video_thumbnail: ^0.2.5+1
  mime: ^0.9.7
  just_audio: ^0.6.9
  modal_bottom_sheet: ^1.0.0+1
  emojis: ^0.9.3
  highlight: ^0.6.0
  flutter_highlight: ^0.6.0
  syncfusion_flutter_datepicker: ^18.4.41-beta
  syncfusion_flutter_core: ^18.4.35
  solar_datepicker: ^0.0.1+1
  shamsi_date: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
