# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Deploy a new internal version to the Google Play Store'
  lane :internal do
    versions = google_play_track_version_codes(track: "internal")
    version_code = versions[0]
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    supply(
      track: 'internal',
      version_code: version_code
      skip_upload_changelogs: true,
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].to_s
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
